### ISSUE TITLE
Develop build infrastructure

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/libaccessom2#1]
Develop spack based build infrastructure.

**Comment by harshula** [comment]
The spack-build branch is ready for review and testing:
https://github.com/ACCESS-NRI/libaccessom2/compare/master...ACCESS-NRI:libaccessom2:spack-build

**Comment by harshula** [comment]
The Spack package file is: https://github.com/ACCESS-NRI/spack_packages/blob/accessom2-build/packages/libaccessom2/package.py

**Comment by harshula** [comment]
PR: https://github.com/ACCESS-NRI/spack_packages/pull/5
