### ISSUE TITLE
Try to remove NCI/gadi specific workarounds

### ISSUE THREAD

**Issue by harshula** [ACCESS-NRI/libaccessom2#3]
There appears to be a number of NCI/gadi specific workarounds in the build system of this library and its dependencies. Let's try to eliminate as many as possible.

**Comment by harshula** [comment]
Thanks to @angus-g for showing me his approach to finding NetCDF in https://github.com/angus-g/python-ale/blob/master/CMakeLists.txt . That then led me to finding https://stackoverflow.com/questions/29191855/what-is-the-proper-way-to-use-pkg-config-from-cmake .

Can we simplify it all down to this?:

CMakeLists.txt:
```
-option(FIND_NETCDF "Use FindNetCDF to generate NetCDF configuration" ON)
-if(${FIND_NETCDF})
-  set (NETCDF_F90 "YES")
-  find_package(NetCDF REQUIRED)
-  include_directories(${NETCDF_F90_INCLUDE_DIRS})
-else()
-  set(NETCDF_LIBRARIES netcdff)
-endif()
+find_package(PkgConfig REQUIRED)
+pkg_check_modules(netCDF REQUIRED IMPORTED_TARGET "netcdf-fortran")
 
 # compiler flags for gfortran
 if(CMAKE_Fortran_COMPILER_ID MATCHES GNU)
@@ -168,7 +167,7 @@ set_target_properties(accessom2 PROPERTIES IMPORTED_LOCATION ${LIBACCESSOM2})
 # libforcing test executable
 file(GLOB FORCING_TEST_SOURCES libforcing/test/*.F90)
 add_executable(forcing_test.exe ${FORCING_TEST_SOURCES})
-target_link_libraries(forcing_test.exe forcing util datetime jsonfortran ${NETCDF_LIBRARIES})
+target_link_libraries(forcing_test.exe forcing util datetime jsonfortran PkgConfig::netCDF)
 set_target_properties(forcing_test.exe PROPERTIES
                       RUNTIME_OUTPUT_DIRECTORY libforcing/test/
 )
@@ -176,15 +175,15 @@ set_target_properties(forcing_test.exe PROPERTIES
 # yatm executable
 file(GLOB ATM_SOURCES atm/src/*.F90)
 add_executable(yatm.exe ${ATM_SOURCES})
-target_link_libraries(yatm.exe accessom2 ${NETCDF_LIBRARIES} ${MPI_Fortran_LIBRARIES})
+target_link_libraries(yatm.exe accessom2 PkgConfig::netCDF ${MPI_Fortran_LIBRARIES})
 
 # ice stub executable
 file(GLOB ICE_STUB_SOURCES ice_stub/src/*.F90)
 add_executable(ice_stub.exe ${ICE_STUB_SOURCES})
-target_link_libraries(ice_stub.exe accessom2 ${NETCDF_LIBRARIES} ${MPI_Fortran_LIBRARIES})
+target_link_libraries(ice_stub.exe accessom2 PkgConfig::netCDF ${MPI_Fortran_LIBRARIES})
 
 # ocean stub executable
 file(GLOB OCEAN_STUB_SOURCES ocean_stub/src/*.F90)
 add_executable(ocean_stub.exe ${OCEAN_STUB_SOURCES})
-target_link_libraries(ocean_stub.exe accessom2 ${NETCDF_LIBRARIES} ${MPI_Fortran_LIBRARIES})
+target_link_libraries(ocean_stub.exe accessom2 PkgConfig::netCDF ${MPI_Fortran_LIBRARIES})
 
```

**Comment by aidanheerdegen** [comment]
Hey @harshula. Can you make a PR, or push to a branch so others can test it. Thanks.

**Comment by harshula** [comment]
@aidanheerdegen It's in the [improve-build-system](https://github.com/ACCESS-NRI/libaccessom2/tree/improve-build-system) branch. Perhaps we can try to put more emphasis on code review moving forward?

**Comment by harshula** [comment]
**NetCDF Notes**

re: `find_package(netCDF CONFIGS netCDF-FortranConfig.cmake)`

This file may not be available on Linux distro.

Issue: [netCDF-FortranConfig.cmake.in does not exist #266](https://github.com/Unidata/netcdf-fortran/issues/266)

Fixed by: https://github.com/Unidata/netcdf-fortran/pull/267/commits/2d490af8578628f5b36f7ff0746c5e1f8a735c6d

File: https://github.com/Unidata/netcdf-fortran/blob/main/netCDF-FortranConfig.cmake.in

**Comment by harshula** [comment]
Hi @angus-g , @ScottWales & @daleroberts , What do you think about?: https://github.com/ACCESS-NRI/libaccessom2/issues/3#issuecomment-1283383638

**Comment by harshula** [comment]
NOTE: I'm likely missing an include_directories() after the pkg_check_modules().

**Comment by harshula** [comment]
Now, `libaccessom2` and `oasis-mct` have a build.sh each. They load the relevant modules when run on Gadi. As suggested by `oasis3mct_UserGuide.pdf`, `oasis-mct` still has a separate header file `make.nci` specific to the compiling platform.

**Comment by harshula** [comment]
Fixes:
https://github.com/ACCESS-NRI/libaccessom2/commit/e00f8a2c5c7275bd2ab8033e6f41030b43eb51ae
https://github.com/ACCESS-NRI/libaccessom2/commit/46506d4c3e65b05df1f5be3a362e354d2d8b90a2
https://github.com/ACCESS-NRI/libaccessom2/commit/7ebf6ae3b5fc75df87f170cd041dde4bad1c94ce
